"""
build_partial_label_partition.py — build a partial-label-space partition.

For each client already defined in an existing partition (default:
partitions/tier100), this creates a NEW partition directory
(partitions/<out-name>/client_<id>/) containing:
  - images/  : symlinks to the client's REAL original images (no copying)
  - labels/  : REAL label files, but with every line whose class is not
               in that client's assigned mission profile REMOVED

Ultralytics finds an image's labels by swapping "/images/" for "/labels/"
in the image's own path — since we control both siblings here, YOLO will
automatically find our filtered labels instead of the original ones,
without us touching or duplicating the original dataset at all.

Validation stays on the FULL, unfiltered clean_val.txt from the source
partition — we want to measure each client's restricted training against
real ground truth, not against its own limited view. That is the whole
point of the partial-label-space experiment.

See docs/partial_label_profiles.md for the full methodology behind the
profile assignments used here.
"""
from pathlib import Path
import argparse
import sys

from assign_label_profiles import assign_profiles, PROFILES, CLASS_NAMES

REPO = Path(__file__).resolve().parents[1]


def filter_label_file(src_label: Path, allowed_classes: set[int]) -> list[str]:
    """Return only the lines of src_label whose class id is in
    allowed_classes. Missing source file -> empty list (no objects)."""
    if not src_label.is_file():
        return []
    kept = []
    for line in src_label.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        class_id = int(line.split()[0])
        if class_id in allowed_classes:
            kept.append(line)
    return kept


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source-partition", default="tier100",
                    help="existing partition to build the partial-label "
                         "version from (default: tier100)")
    ap.add_argument("--out-name", default="tier100_partial_labels",
                    help="name for the new partition directory")
    args = ap.parse_args()

    src_root = REPO / f"federated/experiments/partitions/{args.source_partition}"
    if not src_root.is_dir():
        sys.exit(f"ERROR: source partition not found: {src_root}")

    out_root = REPO / f"federated/experiments/partitions/{args.out_name}"
    out_root.mkdir(parents=True, exist_ok=True)

    assignment = assign_profiles()

    # clean_val.txt stays FULL/unfiltered — copy the reference, don't alter it
    src_clean_val = src_root / "clean_val.txt"
    if not src_clean_val.is_file():
        sys.exit(f"ERROR: {src_clean_val} not found")
    out_clean_val = out_root / "clean_val.txt"
    out_clean_val.write_text(src_clean_val.read_text())

    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(CLASS_NAMES))

    n_clients_done = 0
    for client_id, profile_name in sorted(assignment.items()):
        src_client_dir = src_root / f"client_{client_id}"
        src_train_txt = src_client_dir / "train.txt"
        if not src_train_txt.is_file():
            print(f"WARNING: skipping {client_id} — no train.txt in source partition")
            continue

        allowed_classes = set(PROFILES[profile_name])

        out_client_dir = out_root / f"client_{client_id}"
        out_images_dir = out_client_dir / "images"
        out_labels_dir = out_client_dir / "labels"
        out_images_dir.mkdir(parents=True, exist_ok=True)
        out_labels_dir.mkdir(parents=True, exist_ok=True)

        image_paths = [Path(p) for p in src_train_txt.read_text().splitlines() if p.strip()]

        new_image_paths = []
        n_lines_before = 0
        n_lines_after = 0
        for img_path in image_paths:
            # symlink the image itself (no copy — saves disk, images unchanged)
            link_path = out_images_dir / img_path.name
            if not link_path.exists():
                link_path.symlink_to(img_path)
            new_image_paths.append(str(link_path.resolve()))

            # filter the matching label file
            src_label_path = img_path.parent.parent / "labels" / (img_path.stem + ".txt")
            n_lines_before += len(src_label_path.read_text().splitlines()) if src_label_path.is_file() else 0
            kept_lines = filter_label_file(src_label_path, allowed_classes)
            n_lines_after += len(kept_lines)
            out_label_path = out_labels_dir / (img_path.stem + ".txt")
            out_label_path.write_text("\n".join(kept_lines) + ("\n" if kept_lines else ""))

        train_txt = out_client_dir / "train.txt"
        train_txt.write_text("\n".join(new_image_paths) + "\n")

        (out_client_dir / "data.yaml").write_text(
            f"# auto-generated by build_partial_label_partition.py — do not edit\n"
            f"# client={client_id} profile={profile_name} "
            f"classes={[CLASS_NAMES[i] for i in PROFILES[profile_name]]}\n"
            f"train: {train_txt}\n"
            f"val: {out_clean_val}\n"
            f"names:\n{names_block}\n"
        )

        pct_kept = 100 * n_lines_after / n_lines_before if n_lines_before else 0
        print(f"client_{client_id}: profile={profile_name} "
              f"{len(image_paths)} images, "
              f"{n_lines_before} -> {n_lines_after} label lines kept ({pct_kept:.1f}%)")
        n_clients_done += 1

    print(f"\nwrote {n_clients_done} client partitions under {out_root}")


if __name__ == "__main__":
    main()
