"""
partition_by_location.py — generate per-client YOLO datasets from the registry.

Reads federated/experiments/registry/clients.csv, selects clients eligible at
the chosen tier, and writes per-client train lists + YAMLs plus one shared
clean global validation list. No images are copied; only path lists.

Deterministic: no randomness (clients train on all local images; validation
is the shared clean global val set).
"""

from pathlib import Path
import argparse
import csv
import sys

REPO = Path(__file__).resolve().parents[1]
REGISTRY = REPO / "federated/experiments/registry/clients.csv"
TRAIN_IMG = REPO / "data/VisDrone-DET/VisDrone2019-DET-train/images"
VAL_IMG   = REPO / "data/VisDrone-DET/VisDrone2019-DET-val/images"
IMG_EXTS = {".jpg", ".jpeg", ".png"}

# Must match visdrone.yaml — verify against your existing training config.
CLASS_NAMES = ["pedestrian", "people", "bicycle", "car", "van", "truck",
               "tricycle", "awning-tricycle", "bus", "motor"]

def label_for(img_path: Path) -> Path:
    return img_path.parent.parent / "labels" / (img_path.stem + ".txt")

def list_images(img_dir: Path, prefix: str | None = None) -> list[Path]:
    imgs = sorted(p for p in img_dir.iterdir()
                  if p.suffix.lower() in IMG_EXTS
                  and (prefix is None or p.name.startswith(prefix + "_")))
    return imgs

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tier", type=int, choices=[20, 50, 100], required=True,
                    help="minimum images per client (eligibility tier)")
    args = ap.parse_args()

    if not REGISTRY.is_file():
        sys.exit(f"ERROR: registry not found: {REGISTRY} "
                 "(run inspect_locations.py first)")

    with REGISTRY.open() as fh:
        rows = list(csv.DictReader(fh))

    eligible = [r for r in rows if r[f"eligible_{args.tier}"] == "1"]
    overlap_groups = {r["group_id"] for r in rows if r["train_val_overlap"] == "1"}
    print(f"tier >= {args.tier}: {len(eligible)} eligible clients, "
          f"{len(overlap_groups)} overlap groups excluded from clean val")

    out_root = REPO / f"federated/experiments/partitions/tier{args.tier}"
    out_root.mkdir(parents=True, exist_ok=True)

    # ---- shared clean global validation list -------------------------
    val_imgs = [p for p in list_images(VAL_IMG)
                if p.name.split("_", 1)[0] not in overlap_groups]
    missing = [p for p in val_imgs if not label_for(p).is_file()]
    if missing:
        sys.exit(f"ERROR: {len(missing)} val images missing labels, "
                 f"e.g. {missing[0].name}")
    clean_val_txt = out_root / "clean_val.txt"
    clean_val_txt.write_text("\n".join(str(p) for p in val_imgs) + "\n")
    print(f"clean global val: {len(val_imgs)} images -> {clean_val_txt}")

    # ---- per-client lists and YAMLs -----------------------------------
    summary = []
    for r in eligible:
        gid = r["group_id"]
        client_dir = out_root / f"client_{gid}"
        client_dir.mkdir(exist_ok=True)

        imgs = list_images(TRAIN_IMG, prefix=gid)
        if len(imgs) != int(r["n_train_images"]):
            sys.exit(f"ERROR: client {gid}: registry says "
                     f"{r['n_train_images']} images, found {len(imgs)}")
        missing = [p for p in imgs if not label_for(p).is_file()]
        if missing:
            sys.exit(f"ERROR: client {gid}: {len(missing)} images missing "
                     f"labels, e.g. {missing[0].name}")

        train_txt = client_dir / "train.txt"
        train_txt.write_text("\n".join(str(p) for p in imgs) + "\n")

        names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(CLASS_NAMES))
        (client_dir / "data.yaml").write_text(
            f"# auto-generated by partition_by_location.py — do not edit\n"
            f"train: {train_txt}\n"
            f"val: {clean_val_txt}\n"
            f"names:\n{names_block}\n"
        )
        summary.append({"client_id": f"client_{gid}", "group_id": gid,
                        "n_train_images": len(imgs),
                        "origin_inferred": r["origin_inferred"]})

    with (out_root / "partition_summary.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(summary[0].keys()))
        w.writeheader()
        w.writerows(summary)
    print(f"wrote {len(summary)} client partitions under {out_root}")

if __name__ == "__main__":
    main()
